### ISSUE TITLE
Shorten ODK Validate error output

### ISSUE THREAD

**Issue by prabhasp** [SEL-Columbia/pyxform#84]
from something like:

```
ODK Validate Errors: Invalid XPath expression [if((/GS_OM_HEALTH_FACILITY_XFORM_2013_03_20/HF700_2 != -9990) and?(/GS_OM_HEALTH_FACILITY_XFORM_2013_03_20/HF701_2 != -9990), /GS_OM_HEALTH_FACILITY_XFORM_2013_03_20/HF701_2 + /GS_OM_HEALTH_FACILITY_XFORM_2013_03_20/HF700_2, -9990)]! java.lang.NullPointerException java.lang.NullPointerException at org.javarosa.core.model.FormDef.addTriggerable(FormDef.java:524) at org.javarosa.xform.parse.XFormParser.processStandardBindAttributes(XFormParser.java:1501) at org.javarosa.xform.parse.XFormParser.parseBind(XFormParser.java:1521) at org.javarosa.xform.parse.XFormParser.parseModel(XFormParser.java:460) at org.javarosa.xform.parse.XFormParser.access$200(XFormParser.java:78) at org.javarosa.xform.parse.XFormParser$3.handle(XFormParser.java:153) at org.javarosa.xform.parse.XFormParser.parseElement(XFormParser.java:375) at org.javarosa.xform.parse.XFormParser.parseElement(XFormParser.java:386) at org.javarosa.xform.parse.XFormParser.parseElement(XFormParser.java:386) at org.javarosa.xform.parse.XFormParser.parseDoc(XFormParser.java:321) at org.javarosa.xform.parse.XFormParser.parse(XFormParser.java:272) at org.javarosa.xform.util.XFormUtils.getFormFromInputStream(XFormUtils.java:72) at org.odk.validate.FormValidator.validate(FormValidator.java:322) at org.odk.validate.FormValidator.(FormValidator.java:95) at org.odk.validate.FormValidator.main(FormValidator.java:82) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:616) at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58) >> Something broke the parser. See above for a hint. Result: Invalid
```

to something like:

```
ODK Validate Errors: Invalid XPath expression [if((/GS_OM_HEALTH_FACILITY_XFORM_2013_03_20/HF700_2 != -9990) and?(/GS_OM_HEALTH_FACILITY_XFORM_2013_03_20/HF701_2 != -9990), /GS_OM_HEALTH_FACILITY_XFORM_2013_03_20/HF701_2 + /GS_OM_HEALTH_FACILITY_XFORM_2013_03_20/HF700_2, -9990)]! >> Something broke the parser. See above for a hint. Result: Invalid
```

Does anyone disagree?

**Comment by prabhasp** [comment]
(Would be even better for users if we back-translated `/GS_OM_HEALTH_FACILITY_XFORM_2013_03_20/HF700_2` to `${HF700_2}` . If this isn't always going to be correct, outputting both could be an option worth considering.
